### ISSUE TITLE
SEIR Model Evaluation

### ISSUE THREAD

**Issue by cheung-ho-lum** [NickVeld/model_evaluation#1]
Hey guys,

The long story short is that it's almost inevitable that group 3 will have SEIR for NYC and SEIR global numbers as some results of our modeling. I mean... we should just check it (really, fit it) against the numbers for ourselves, right? But... perhaps this is something you guys are doing?

I'm not clear on the division of labor here. But I'll post this thought.

**Comment by NickVeld** [comment]
Yep, this tool is going to make reports about the similarity of your numbers and real data

**Comment by NickVeld** [comment]
Done, in v0.1
